---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

images:
- name: profile-service-api-img
  newName: skaffold-int23-react-profile-service-api-local

resources:
- pvc.yaml
- ../../base
- gateway.yaml
- service.yaml

patches:
- target:
    kind: VirtualService
    name: profile-service-api
  path: virtual-service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: mssql-profile-db-secret
  literals:
  - sa_password='aG00dP@ssw0rd'