version: "3.2"

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: internship-db
    ports:
      - "1433:1433"
    networks:
      -  nvisia-profile-service-network
    environment:
      SA_PASSWORD: "aG00dP@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:  
      - ./:/local-db-setup/
    command: ./local-db-setup/entrypoint.sh
    

# need to create network before docker-compose up -d, with:
# docker network create local_default
networks:
  nvisia-profile-service-network:
    name: nvisia-profile-service-network
      
