---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mssql-statefulset.yaml
- deployment.yaml
- service.yaml
- virtual-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: mssql-profile-db-setup-cm
  files:
  - ./mssql-config/entrypoint.sh
  - ./mssql-config/init-db.sh
  - ./mssql-config/schema.sql